name: Complete release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: 'Release tag'
        type: string
  release:
    types: [published]
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  automation:
    uses: ./.github/workflows/automation.yml
    secrets: inherit

  post-release:
    runs-on: ubuntu-latest

    needs:
    - automation

    if: needs.automation.outputs.enabled

    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
        token: ${{ secrets[needs.automation.outputs.token-secret-name] }}

    - name: Create GitHub Pull Request to update stable build version in props
      if: |
        (github.ref_type == 'tag' && startsWith(github.ref_name, 'core-') && !contains(github.ref_name, '-alpha') && !contains(github.ref_name, '-beta') && !contains(github.ref_name, '-rc'))
        || (inputs.tag && startsWith(inputs.tag, 'core-') && !contains(inputs.tag, '-alpha') && !contains(inputs.tag, '-beta') && !contains(inputs.tag, '-rc'))

      env:
        GH_TOKEN: ${{ secrets[needs.automation.outputs.token-secret-name] }}

      shell: pwsh
      run: |
        Import-Module .\build\scripts\post-release.psm1

        CreateStableVersionUpdatePullRequest `
          -gitRepository '${{ github.repository }}' `
          -tag '${{ inputs.tag || github.ref_name }}' `
          -gitUserName '${{ needs.automation.outputs.username }}' `
          -gitUserEmail '${{ needs.automation.outputs.email }}'
